# Generated by Django 4.2.7 on 2023-12-08 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_name', models.CharField(max_length=150)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('future_investment_date', models.DateField(blank=True, null=True, verbose_name='Future investment date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(max_length=150)),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('future_income_date', models.DateField(blank=True, null=True, verbose_name='Future income date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=150)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('future_expense_date', models.DateField(blank=True, null=True, verbose_name='Future expense date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
