# Generated by Django 4.2.7 on 2023-12-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
    ]
