# Generated by Django 4.2.7 on 2023-12-04 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20231204_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='income',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
